'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4984
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BarcodeReaderDemo.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property picboxFirst_Disabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picboxFirst_Disabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picboxFirst_Down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picboxFirst_Down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picboxFirst_Enter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picboxFirst_Enter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picboxFirst_Leave() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picboxFirst_Leave", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picboxLast_Disabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picboxLast_Disabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picboxLast_Down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picboxLast_Down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picboxLast_Enter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picboxLast_Enter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picboxLast_Leave() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picboxLast_Leave", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picboxNext_Disabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picboxNext_Disabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picboxNext_Down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picboxNext_Down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picboxNext_Enter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picboxNext_Enter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picboxNext_Leave() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picboxNext_Leave", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picboxPrevious_Disabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picboxPrevious_Disabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picboxPrevious_Down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picboxPrevious_Down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picboxPrevious_Enter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picboxPrevious_Enter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picboxPrevious_Leave() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picboxPrevious_Leave", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
